name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Build React application
      run: |
        npm run build

    - name: Run SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@2.3.1
      with:
        args: -Dsonar.projectKey=LoicRbn_GithubCiCd -Dsonar.organization=loicrbn
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}